apiVersion: apps/v1
kind: Deployment
metadata:
  name: endless-calls
  labels:
    app: endless-calls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endless-calls
  template:
    metadata:
      labels:
        app: endless-calls
    spec:
      containers:
      - name: endless-calls
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget -q -O- http://php-apache;done"]
      
      